Fix #14 - Using stubbed collections for publication tests
Using a stub-collection with johanbrook:meteor-publication-collector
sometimes causes the error

> Error: Can't publish a cursor from a collection without a name.

The simple fix for this is to create a localCollection with a name. To
ensure that the stubbed collection doesn't connect to an existing local
collection that was stubbed previously, we randomise the name.